version: "3.7"
services:
    app:
        build:
            args:
                user: flok
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - mysql
        ports:
            - 8080:8080
        environment:
            - WAIT_HOSTS=mysql:3306
            - WAIT_HOSTS_TIMEOUT=7200
            - WAIT_SLEEP_INTERVAL=30
            - WAIT_HOST_CONNECT_TIMEOUT=30
            - TZ=Africa/Lagos
        links:
            - mysql
        container_name: myapp
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
    mysql:
        image: mysql:5.7.12
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "9099:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: hospital-backend-database

    nginx:
        image: nginx:1.17-alpine
        restart: unless-stopped
        links:
            - app
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./nginx/logs:/var/log/nginx
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - mysql
            - app
